<?php
/* The 30 case-study queries used by the SQL Lab (run live via api.php).
   Queries that reference the absent pid 123 are demoed with pid 110 so
   the app shows real output; this is flagged in the UI. */
$QUERIES = [
 ["Complete details of all flights to New Delhi.",
  "SELECT * FROM flight WHERE dest = 'New Delhi';"],
 ["All flights from Chennai to New Delhi.",
  "SELECT * FROM flight WHERE src = 'Chennai' AND dest = 'New Delhi';"],
 ["Flight numbers for passenger 123, to Chennai before 06/11/2020.",
  "SELECT DISTINCT b.fid FROM booking b JOIN flight f ON b.fid=f.fid\nWHERE b.pid='110' AND f.dest='Chennai' AND f.fdate<'2020-11-06';",
  "Case study uses pid 123 (absent); shown with pid 110."],
 ["Passenger names who have at least one booking.",
  "SELECT DISTINCT p.pname FROM passenger p JOIN booking b ON p.pid=b.pid;"],
 ["Passenger names who have no bookings.",
  "SELECT pname FROM passenger WHERE pid NOT IN (SELECT pid FROM booking);"],
 ["Agencies in the same city as passenger 123.",
  "SELECT aname FROM agency WHERE acity=(SELECT pcity FROM passenger WHERE pid='110');",
  "Case study uses pid 123; shown with pid 110 (Bhopal)."],
 ["Flights on BOTH 01 & 02 Dec 2020 at 16:00 (same route).",
  "SELECT * FROM flight WHERE fdate='2020-12-01' AND time='16:00'\n  AND src  IN (SELECT src  FROM flight WHERE fdate='2020-12-02' AND time='16:00')\n  AND dest IN (SELECT dest FROM flight WHERE fdate='2020-12-02' AND time='16:00');"],
 ["Flights on EITHER 01 or 02 Dec 2020 at 16:00.",
  "SELECT * FROM flight WHERE time='16:00' AND fdate IN ('2020-12-01','2020-12-02');"],
 ["Agencies with no bookings for passenger 123.",
  "SELECT aname FROM agency WHERE aid NOT IN (SELECT aid FROM booking WHERE pid='110');",
  "Case study uses pid 123; shown with pid 110."],
 ["All male passengers associated with the Jet agency.",
  "SELECT DISTINCT p.pid,p.pname,p.pgender,p.pcity\nFROM passenger p JOIN booking b ON p.pid=b.pid JOIN agency a ON b.aid=a.aid\nWHERE p.pgender='Male' AND a.aname='Jet';"],
 ["Passengers who booked more than one flight.",
  "SELECT p.pid,p.pname,COUNT(*) AS flights\nFROM passenger p JOIN booking b ON p.pid=b.pid\nGROUP BY p.pid,p.pname HAVING COUNT(*)>1;"],
 ["Agency that handled the maximum number of bookings.",
  "SELECT a.aid,a.aname,COUNT(*) AS total\nFROM agency a JOIN booking b ON a.aid=b.aid\nGROUP BY a.aid,a.aname ORDER BY total DESC LIMIT 1;"],
 ["Passengers who booked via agencies in a different city.",
  "SELECT DISTINCT p.pid,p.pname FROM passenger p JOIN booking b ON p.pid=b.pid\nJOIN agency a ON b.aid=a.aid WHERE p.pcity<>a.acity;"],
 ["Flights with more than 5 passengers booked.",
  "SELECT f.fid,COUNT(*) AS pax FROM flight f JOIN booking b ON f.fid=b.fid\nGROUP BY f.fid HAVING COUNT(*)>5;"],
 ["Passenger who booked the earliest flight.",
  "SELECT p.pid,p.pname,f.fid,f.fdate,f.time\nFROM booking b JOIN flight f ON b.fid=f.fid JOIN passenger p ON b.pid=p.pid\nORDER BY f.fdate,f.time LIMIT 1;"],
 ["Passengers who booked to more than one destination.",
  "SELECT p.pid,p.pname,COUNT(DISTINCT f.dest) AS dests\nFROM passenger p JOIN booking b ON p.pid=b.pid JOIN flight f ON b.fid=f.fid\nGROUP BY p.pid,p.pname HAVING COUNT(DISTINCT f.dest)>1;"],
 ["Agencies that never handled a booking.",
  "SELECT aname FROM agency WHERE aid NOT IN (SELECT aid FROM booking);"],
 ["Flights that have no bookings.",
  "SELECT * FROM flight WHERE fid NOT IN (SELECT fid FROM booking);"],
 ["Passengers who booked ALL available flights.",
  "SELECT p.pid,p.pname FROM passenger p JOIN booking b ON p.pid=b.pid\nGROUP BY p.pid,p.pname HAVING COUNT(DISTINCT b.fid)=(SELECT COUNT(*) FROM flight);"],
 ["Most frequently travelled destination.",
  "SELECT f.dest,COUNT(*) AS trips FROM booking b JOIN flight f ON b.fid=f.fid\nGROUP BY f.dest ORDER BY trips DESC LIMIT 1;"],
 ["Passengers who booked on consecutive dates.",
  "SELECT DISTINCT b1.pid FROM booking b1 JOIN booking b2\n  ON b1.pid=b2.pid AND b2.fdate = DATE_ADD(b1.fdate, INTERVAL 1 DAY);"],
 ["Total passengers travelling from each source city.",
  "SELECT f.src,COUNT(*) AS pax FROM booking b JOIN flight f ON b.fid=f.fid\nGROUP BY f.src ORDER BY pax DESC;"],
 ["Agencies that booked for both male and female passengers.",
  "SELECT a.aid,a.aname FROM agency a JOIN booking b ON a.aid=b.aid\nJOIN passenger p ON b.pid=p.pid GROUP BY a.aid,a.aname HAVING COUNT(DISTINCT p.pgender)=2;"],
 ["Flight with the highest number of bookings.",
  "SELECT f.fid,f.src,f.dest,COUNT(*) AS bookings\nFROM flight f JOIN booking b ON f.fid=b.fid\nGROUP BY f.fid,f.src,f.dest ORDER BY bookings DESC LIMIT 1;"],
 ["Passengers who booked through only one agency.",
  "SELECT p.pid,p.pname FROM passenger p JOIN booking b ON p.pid=b.pid\nGROUP BY p.pid,p.pname HAVING COUNT(DISTINCT b.aid)=1;"],
 ["Agencies whose bookings exceed the average.",
  "SELECT t.aid,a.aname,t.total FROM (SELECT aid,COUNT(*) total FROM booking GROUP BY aid) t\nJOIN agency a ON a.aid=t.aid\nWHERE t.total > (SELECT AVG(cnt) FROM (SELECT COUNT(*) cnt FROM booking GROUP BY aid) x);"],
 ["Passengers who never travelled to New Delhi.",
  "SELECT pname FROM passenger WHERE pid NOT IN\n  (SELECT b.pid FROM booking b JOIN flight f ON b.fid=f.fid WHERE f.dest='New Delhi');"],
 ["Number of bookings done on each date.",
  "SELECT fdate,COUNT(*) AS bookings FROM booking GROUP BY fdate ORDER BY fdate;"],
 ["Passengers whose names start with 'A'.",
  "SELECT * FROM passenger WHERE pname LIKE 'A%';"],
 ["Flights where source and destination differ.",
  "SELECT * FROM flight WHERE src <> dest;"],
];
